name: debasish_portfolio
description: A production-ready Flutter Web Portfolio for Debasish Kumar Das.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Design
  google_fonts: ^6.1.0
  font_awesome_flutter 10.9.0
  url_launcher: ^6.2.2
  
  # Animations (Lightweight)
  simple_animations: ^5.0.2
  visibility_detector: ^0.4.0+2
  animate_do: ^3.3.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
